// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGZ8DrZ4XgiQBOld-ajZzT94jeRKrlCo',
    appId: '1:1046404480213:web:5316464e9329e9d2afb65c',
    messagingSenderId: '1046404480213',
    projectId: 'farematch-driver-app',
    authDomain: 'farematch-driver-app.firebaseapp.com',
    storageBucket: 'farematch-driver-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7agoiIxrpHlh4w7khIQOGF2tLVUtLy38',
    appId: '1:1046404480213:android:684765fc64e98413afb65c',
    messagingSenderId: '1046404480213',
    projectId: 'farematch-driver-app',
    storageBucket: 'farematch-driver-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAajP_v-rcy71-Rz5jCrDjojLiwo9IjRs',
    appId: '1:1046404480213:ios:486184cdd8c5ccc6afb65c',
    messagingSenderId: '1046404480213',
    projectId: 'farematch-driver-app',
    storageBucket: 'farematch-driver-app.firebasestorage.app',
    iosBundleId: 'com.example.farematchDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAajP_v-rcy71-Rz5jCrDjojLiwo9IjRs',
    appId: '1:1046404480213:ios:486184cdd8c5ccc6afb65c',
    messagingSenderId: '1046404480213',
    projectId: 'farematch-driver-app',
    storageBucket: 'farematch-driver-app.firebasestorage.app',
    iosBundleId: 'com.example.farematchDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUGZ8DrZ4XgiQBOld-ajZzT94jeRKrlCo',
    appId: '1:1046404480213:web:7e37d84eb8352bcfafb65c',
    messagingSenderId: '1046404480213',
    projectId: 'farematch-driver-app',
    authDomain: 'farematch-driver-app.firebaseapp.com',
    storageBucket: 'farematch-driver-app.firebasestorage.app',
  );
}
